/mv_camera:
  ros__parameters:
    analog_gain: 15
    # camera_info_url: package://mindvision_camera/config/camera_info.yaml
    camera_name: mv_camera
    frame_id: "camera_optical_frame"
    exposure_time: 10000
    flip_image: false
    gamma: 100
    rgb_gain:
      b: 100
      g: 125
      r: 160
    saturation: 100