/mv_camera:
  ros__parameters:
    # analog_gain: 10
    camera_info_url: package://mindvision_camera/config/camera_info.yaml
    camera_name: mv_camera
    frame_id: "camera_optical_frame"
    exposure_time: 7000
    flip_image: false
    gamma: 80
    rgb_gain:
      b: 100
      g: 125
      r: 160
    saturation: 100

/armor_detector:
  ros__parameters:
    debug: true

    detect_color: 1
    binary_thres: 140

    classifier_threshold: 0.6
    ignore_classes: ["negative"]

    is_record: false
    save_video_path: armor.avi
    save_video_fps: 100
    save_video_width: 1280
    save_video_height: 1024
    
    light:
      max_angle: 40.0
      max_ratio: 0.8
      min_ratio: 0.05

    # armor:
    #   max_angle: 35.0
    #   max_center_ratio: 1.6
    #   min_center_ratio: 0.4
    #   min_light_ratio: 0.6
    #   max_large_center_distance: 5.0
    #   min_large_center_distance: 2.8
    #   max_small_center_distance: 2.8
    #   min_small_center_distance: 0.8

/armor_tracker:
  ros__parameters:
    target_frame: shooter_link

    ekf:
      sigma2_q_xyz: 5e-2
      sigma2_q_yaw: 1e1
      sigma2_q_r: 80.0

      r_xyz_factor: 2e-4
      r_yaw: 5e-3

    tracker:
      max_match_distance: 0.15
      tracking_thres: 3
      lost_time_thres: 0.6

/trt_armor_detector:
  ros__parameters:
    subscribe_compressed: false
    active: true
    debug: true
    model_path: 20230415.trt
    # 0 for blue, 1 for red
    detect_color: 0
    prob_threshold: 0.25 
    nms_threshold: 0.45

/lc_serial_driver:
  ros__parameters:
    device_name: /dev/ttyACM0
    baud_rate: 115200
    flow_control: none
    parity: none
    stop_bits: "1"

    fps: 100
    is_try: false
    
    is_pitch_gain: true
    is_track: true
    shoot_delay: 0.4
    shoot_delay_spin_: 0.2
    shoot_speed: 14.4

    x_gain: 0.0
    y_gain: 0.0
    z_gain: 0.0
    pitch_gain_: 0.15
    
    
    # 龙格库塔法求解落点的迭代次数
    R_K_iter: 50
    # 使用迭代法求解pitch补偿的最大迭代次数
    max_iter: 10
    # 停止迭代的最小误差(单位m)
    stop_error: 0.001

/video_pub:
  ros__parameters:
    fps: 100
    video_path: red_1_5m.avi
    # video_path: armor.avi
