/mv_camera:
  ros__parameters:
    analog_gain: 15
    camera_info_url: package://mindvision_camera/config/camera_info.yaml
    camera_name: mv_camera
    frame_id: "camera_optical_frame"
    exposure_time: 5000
    flip_image: false
    gamma: 100
    rgb_gain:
      b: 100
      g: 125
      r: 160
    saturation: 100

/armor_detector:
  ros__parameters:
    active: true
    debug: true
    detect_color: 1
    min_lightness: 250

    light:
      max_angle: 40.0
      max_ratio: 0.55
      min_ratio: 0.1

    armor:
      max_angle: 35.0
      max_large_center_distance: 5.0
      max_small_center_distance: 2.8
      min_large_center_distance: 3.2
      min_light_ratio: 0.6
      min_small_center_distance: 0.8

    classifier:
      threshold: 0.7

/armor_tracker_node:
  ros__parameters:
    debug: true
    
    ekf:
      Q00: 0.01
      Q11: 0.1
      Q22: 0.01
      Q33: 0.1
      Q44: 0.01
      Q55: 0.1
      R00: 0.05
      R11: 0.05
      R22: 0.05
      
    lost_count_threshold: 10
    match_count_threshold: 10
    max_lost_distance: 0.4
    max_lost_time: 0.5
    shoot_v: 15.0

/serial_driver:
  ros__parameters:
    device_name: /dev/ttyACM0
    baud_rate: 115200
    flow_control: none
    parity: none
    stop_bits: "1"
